before_script:
  - sudo apt-get -y -qq install curl make libgc-dev libgles2-mesa-dev
  - export PATH=$PATH:$PWD/tools/rock/bin:$PWD/tools/sam
  - mkdir tools
  - export OOC_LIBS=$PWD/tools 
  - # otherwise, PWD/sdk.use will be used instead of PWD/tools/rock/sdk.use and rock will fail to compile.
  - # rock will look for .use files not in OOC_LIBS, but in subfolders to OOC_LIBS - in this case, OOC_LIBS/rock.
  - (cd tools && git clone --depth=1 git://github.com/cogneco/rock.git -b master)
  - (cd tools && git clone --depth=1 git://github.com/cogneco/sam.git)
  - (cd tools/rock && make -s rescue)
  - (cd tools/sam && rock -v)

script:
  - export OOC_LIBS=$PWD/..
  - # because now we want to use ooc-kean/sdk.use, i.e. PWD/sdk.use.
  - (cd test && rock -v -r --gc=off -lpthread -O2 draw/gpu/pc/ToRasterTest)
  - (cd test && rock -v -r --gc=off -lpthread -O2 draw/gpu/pc/WindowTest)
  - sam test --rockargs --gc=off,-lpthread,-O2
  - sam test

