before_script:
  - sudo apt-get update
  - sudo apt-get -y -qq install libgc-dev
  - sudo apt-get -y -qq install libgles2-mesa-dev
  - sudo apt-get -y -qq install wget
  - tmp="$(wget -O - https://github.com/cogneco/rock/releases/latest | grep -o '\<download/rock_.*deb\>')"
  - wget https://github.com/cogneco/rock/releases/$tmp
  - sudo dpkg --install ${tmp##*/}
  - ls /usr/include
  - export PATH=$PATH:$PWD/tools/rock/bin:$PWD/tools/sam
  - mkdir tools
  - export OOC_LIBS=$PWD/..
  - # otherwise, PWD/sdk.use will be used instead of PWD/tools/rock/sdk.use and rock will fail to compile.
  - # rock will look for .use files not in OOC_LIBS, but in subfolders to OOC_LIBS - in this case, OOC_LIBS/rock.
  - (cd tools && git clone --depth=1 git://github.com/cogneco/sam.git)
  - (cd tools/sam && rock -v)

script:
  - ./test.sh nogpu -Dnogpu
